# Generated by Django 3.1 on 2020-08-11 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.IntegerField(max_length=9)),
                ('direccion', models.CharField(max_length=256)),
                ('modelo', models.CharField(max_length=256)),
                ('cantidad', models.IntegerField(max_length=1)),
                ('instagram', models.CharField(max_length=256)),
                ('fecha_pedido', models.DateTimeField()),
                ('fecha_envio', models.CharField(max_length=256)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artesanoapp.estado')),
            ],
        ),
    ]
