# Generated by Django 3.1 on 2020-08-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artesanoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
