# Generated by Django 3.1 on 2020-08-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artesanoapp', '0003_auto_20200811_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cantidad',
            field=models.IntegerField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_envio',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_pedido',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='instagram',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modelo',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
