# Generated by Django 3.1 on 2020-08-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artesanoapp', '0005_auto_20200811_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cantidad',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
